version: "3.7"
services:
  web:
      container_name: container_jairo
      image: sernikov/apachenodephp7.4:1.1
      ports:
          - 800:80
      volumes:
          - ./:/var/www/html
      stdin_open: true
      tty: true
      restart: always
      depends_on:
        - db
        - db_test
  db_test:
    container_name: mysql_test_docker
    image: mysql:5.7
    volumes:
      - ./mysql_test:/var/lib/mysql
    environment:
      MYSQL_USER: admin
      MYSQL_DATABASE: fitcard
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8565:3306"
  db:
    container_name: mysql_docker
    image: mysql:5.7
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_USER: admin
      MYSQL_DATABASE: fitcard
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8560:3306"
